# PBS flags
queue: normal
qsub_flags: -lother=hyperthread
project: g40
walltime: 5:00:00
ncpus: 2698
mem: 5070GB 
jobname: mom01v5

qsub_flags: -W umask=027

#priority: 15
#collate: true
#collate_mem: 98Gb
#collate_walltime: 05:00:00
#collate_ncpus: 4
#collate_queue: express
#collate_flags: -n4 -z -m -r

collate_walltime: 24:00:00
collate_mem: 128GB
collate_ncpus: 16
collate_queue: express
collate_flags: -n4 -z -m -r


# System environment
stacksize: unlimited

# laboratory: /short/v45/pas561/mom
shortpath: /short/v45

# Model config
model: mom
#exe: /short/v45/aph502/mom/bin/mom51_sis_xgrid
#exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel16
exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel14.fpe0.O3
# exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel14.debug
# exe: mom51_sis_ompi184_debug_5kmethods
input:
    - /short/v45/pas561/mom/archive/mom01v5/restart249
    - /short/v45/pas561/mom/input/mom01v2_partial
    - /short/v45/pas561/mom/input/mom01v2
    - /short/v45/pas561/mom/input/sis01_inputs_3600
runlog: true

# mpiP: true

# mpirun:
#      - -mca mpi_preconnect_mpi 1
