# PBS flags
queue: normal
qsub_flags: -lother=hyperthread
project: e14
walltime: 01:00:00
ncpus: 5232
mem: 10464GB

jobname: kds75_cp

#qsub_flags: -W umask=027

priority: 1023
#collate_mem: 98Gb
#collate_walltime: 05:00:00
#collate_ncpus: 4
#collate_queue: express
#collate_flags: -n4 -z -m -r

collate: true
collate_walltime: 10:00:00
collate_mem: 64GB
collate_ncpus: 4
collate_queue: express
collate_flags: -n4 -z -m -r


# System environment
stacksize: unlimited

# laboratory: /short/v45/pas561/mom
shortpath: /short/v45

# Model config
model: mom
#exe: /short/v45/aph502/mom/bin/mom51_sis_xgrid
#exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel16
#exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel14.fpe0.O3
#exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel14.fpe0.O2
exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel14.fpe0.O2.2017
# exe: /short/v45/aph502/mom/bin/fms_MOM_SIS.intel14.debug
# exe: mom51_sis_ompi184_debug_5kmethods
input:
    - /short/v45/pas561/mom/input/mom01Ptrace/ 
    - /short/v45/amh157/mom/input/mom01/levels_kds75 
    - /short/v45/amh157/mom/input/mom01/climatology
    #- /short/v45/amh157/mom/input/mom01/mask_7200
    - /short/v45/amh157/mom/input/mom01/ocean_properties
    - /short/v45/amh157/mom/input/mom01/mosaic_mxw
    - /short/v45/amh157/mom/input/cnyf2

runlog: true

# mpiP: true

# mpirun:
#      - -mca mpi_preconnect_mpi 1
